[default]
mongo_uri = "mongodb://localhost:27017/blog"
title = "Meu Blog"
extensions = [
    "blog.database:configure",
    "blog.commands:configure",
    "flask_bootstrap:Bootstrap",
    "blog.views:configure",
    "blog.plugins:configure",
    "blog.auth:configure",
    "blog.admin:configure",
]
secret_key = "4d0a3413ef3db844910cba74bddd41c596b3a597116c1e8bc16e5ec19bb49dac"
FLASK_ADMIN_SWATCH = "cerulean"